modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="harmonics"
version="${file.jarVersion}"
displayURL="https://github.com/PowerlessReimplemented/HarmonicsCore/"
issueTrackerURL="https://github.com/PowerlessReimplemented/HarmonicsCore/issues"
authors="hnOsmium0001"
displayName="Harmonics Core"
description='''
'''

[[dependencies.harmonics]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"

[[dependencies.harmonics]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"
